_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 23
                - 55
            "4": 3.8.10
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
amp:
    value: false
batch_size:
    value: 32
bilinear:
    value: false
epochs:
    value: 10
img_size:
    value: 512
learning_rate:
    value: 1e-05
lr_scheduler:
    value: <torch.optim.lr_scheduler.ReduceLROnPlateau object at 0x7fe88ddde340>
model:
    value: U-Net
optimizer:
    value: Adam
save_checkpoint:
    value: false
semantic:
    value: false
val_percent:
    value: 10
